### ISSUE TITLE
Would it possibly work with Tapo P115 ?

### ISSUE THREAD

**Issue by lonestaritaly** [miroRucka/tapo-smartplug#1]
hello,
title says it all :-D

**Comment by miroRucka** [comment]
Hi, I think it will work. P115 has consumption measurement and it seems to me that it is just a repackaged p110. Of course, the most important thing is what API it provides directly on the socket, I assume that backward compatibility will be a priority

**Comment by lonestaritaly** [comment]
thanks, gotta test it ASAP
